name: custom
channels:
  - menpo
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - atk=2.25.90
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.3
  - cfitsio=3.430
  - chardet=3.0.4
  - cloudpickle=0.6.0
  - cmake=3.14.4
  - cryptography=2.6.1
  - cryptography-vectors=2.6.1
  - cudatoolkit=9.0
  - curl=7.64.1
  - cycler=0.10.0
  - cython=0.29.9
  - cytoolz=0.9.0.1
  - dask-core=0.19.3
  - dbus=1.13.6
  - decorator=4.3.0
  - descartes=1.1.0
  - expat=2.2.5
  - ffmpeg=4.1.3
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=2.4.1
  - gdk-pixbuf=2.36.12
  - geojson=2.4.1
  - geopandas=0.5.0
  - geos=3.7.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - gobject-introspection=1.58.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.4
  - gstreamer=1.14.4
  - gtk2=2.24.31
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - intel-openmp=2019.0
  - isort=4.3.20
  - jasper=1.900.1
  - joblib=0.13.2
  - jpeg=9c
  - json-c=0.13.1
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - lame=3.100
  - lazy-object-proxy=1.4.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=8.2.0
  - libgdal=2.4.1
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.3
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libuv=1.29.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.9
  - mapclassify=2.0.1
  - markdown=2.6.11
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - mccabe=0.6.1
  - mkl=2019.3
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.2
  - ninja=1.8.2
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - opencv3=3.1.0
  - openh264=1.8.0
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - pango=1.40.14
  - pcre=8.41
  - pillow=6.0.0
  - pip=19.1
  - pixman=0.34.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.3
  - proj4=6.0.0
  - pthread-stubs=0.4
  - pycparser=2.19
  - pylint=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.2.2
  - pysocks=1.7.0
  - python=3.6.7
  - python-dateutil=2.7.3
  - pytorch=1.1.0
  - pywavelets=1.0.3
  - pyzmq=18.0.1
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - rhash=1.3.6
  - rtree=0.8.3
  - scikit-image=0.15.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - tk=8.6.9
  - toolz=0.9.0
  - torchvision=0.3.0
  - tornado=6.0.2
  - typed-ast=1.3.5
  - tzcode=2018g
  - unzip=6.0
  - urllib3=1.24.3
  - websocket-client=0.56.0
  - wheel=0.33.4
  - wrapt=1.11.1
  - x264=1!152.20180806
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.3.3
  - pip:
    - absl-py==0.6.1
    - affine==2.2.1
    - argh==0.26.2
    - astor==0.7.1
    - attrs==18.2.0
    - beautifulsoup4==4.6.3
    - bleach==1.5.0
    - bolt-python==0.7.1
    - boto==2.49.0
    - boto3==1.9.43
    - botocore==1.12.43
    - bs4==0.0.1
    - click==7.0
    - click-plugins==1.0.4
    - cligj==0.5.0
    - docutils==0.14
    - dotmap==1.2.39
    - enum34==1.1.6
    - eo-learn==0.3.3
    - eo-learn-core==0.3.2
    - eo-learn-coregistration==0.3.2
    - eo-learn-features==0.3.3
    - eo-learn-geometry==0.3.3
    - eo-learn-io==0.3.3
    - eo-learn-mask==0.3.2
    - eo-learn-ml-tools==0.3.2
    - fiona==1.8.0
    - flask==1.0.2
    - flask-cors==3.0.7
    - gast==0.2.0
    - geomet==0.2.0.post2
    - gevent==1.3.7
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - gputil==1.3.0
    - gql==0.1.0
    - graphql-core==2.1
    - greenlet==0.4.15
    - grpcio==1.16.1
    - h5py==2.9.0rc1
    - html2text==2018.1.9
    - html5lib==0.9999999
    - imgaug==0.2.6
    - itsdangerous==1.1.0
    - jinja2==2.10
    - jmespath==0.9.3
    - lightgbm==2.2.2
    - llvmlite==0.26.0
    - markupsafe==1.1.0
    - munch==2.3.2
    - nibabel==2.3.1
    - numba==0.41.0
    - nvidia-ml-py3==7.352.0
    - opencv-contrib-python==3.4.2.16
    - opencv-contrib-python-headless==3.4.3.18
    - pandas==0.23.4
    - pathtools==0.1.2
    - phasepack==1.5
    - promise==2.2.1
    - protobuf==3.6.1
    - psutil==5.4.8
    - pydot==1.2.4
    - pyfftw==0.10.4
    - pygit==0.1
    - pygments==2.2.0
    - pyproj==2.1.0
    - pytorch-ignite==0.2.0
    - pytz==2018.5
    - pyyaml==4.2b4
    - rasterio==1.0.8
    - rx==1.6.1
    - s2cloudless==1.2.1
    - s3transfer==0.1.13
    - seaborn==0.9.0
    - sentinelhub==2.4.5
    - sentinelsat==0.13
    - sentry-sdk==0.6.9
    - sh==1.12.14
    - shortuuid==0.5.0
    - smmap2==2.0.5
    - snuggs==1.4.2
    - subprocess32==3.5.3
    - tensorboardx==1.4
    - tensorflow==1.6.0
    - termcolor==1.1.0
    - thunder-python==1.4.2
    - thunder-registration==1.0.1
    - tifffile==2018.11.6
    - torchsummary==1.5.1
    - tqdm==4.27.0
    - utm==0.4.2
    - wandb==0.6.33
    - watchdog==0.9.0
    - werkzeug==0.14.1
    - visdom

